---
title: "Covid Report"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "Marcin Chrapkowicz"
date: "11/15/2020"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyr)
library(formattable)
library(plotly)
knitr::opts_chunk$set(echo = TRUE)
```

```{r cache=TRUE, echo=FALSE}
dirty_data <- read.csv("covid-data.csv", header = TRUE, sep=";")
data <- dirty_data %>%
  group_by(Admission.time) %>%
  fill(PATIENT_ID) %>%
  ungroup() %>%
  mutate(gender = factor(gender,
                         levels = c(1, 2, 0),
                         labels = c("Male", "Female", "Unknown")))
```

```{r}
summary(data)
```
## Executive summary

## Gender statistics
```{r echo=FALSE}
gender_stats <- data %>%
  select(PATIENT_ID, gender) %>%
  distinct() %>%
  group_by(gender) %>%
  tally(name="Number of cases")

formattable(gender_stats, align=c("c","c"))
```